name: Manually build nuget package (used for testing)

on: workflow_dispatch
      
jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --android=13.0
    
    - name: Update ndk location
      run: ln -sfn /Users/runner/Library/Android/sdk/ndk/22.1.7171670 /Users/runner/Library/Android/sdk/ndk-bundle
    
    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: nuget restore Binding/Xam.Plugin.Mixpanel.Android.sln

    - name: Build
      run: |
        cd Binding/
        bash BuildNugetPackage.sh
    
    - uses: actions/upload-artifact@v2
      with:
          name: nuget packages
          path: |
            Binding/*.nupkg
            Binding/*.snupkg

    #- uses: "marvinpinto/action-automatic-releases@latest"
    #  with:
    #    repo_token: "${{ secrets.GITHUB_TOKEN }}"
    #    files: |
    #      Binding/Xam.Plugin.Mixpanel.Android.*.nupkg
    #      Binding/Xam.Plugin.Mixpanel.Android.*.snupkg
          
    #- name: Upload nuget
    #  run: |
    #    cd Binding/
    #    nuget SetApiKey "${{ secrets.NUGET_API_KEY }}"
    #    nuget push *.nupkg -Source https://api.nuget.org/v3/index.json 
