name: Manually build nuget package (used for testing)

on: workflow_dispatch
      
jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Set default Xamarin SDK versions
      run: |
        cat $VM_ASSETS/select-xamarin-sdk-v2.sh
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6_12_11 --android=12.0
        echo "/Library/Frameworks/Mono.framework/Versions"
        ls -la /Library/Frameworks/Mono.framework/Versions
        echo "/Library/Frameworks/Xamarin.iOS.framework/Versions"
        ls -la /Library/Frameworks/Xamarin.iOS.framework/Versions
        echo "/Library/Frameworks/Xamarin.Android.framework/Versions"
        ls -la /Library/Frameworks/Xamarin.Android.framework/Versions
        echo "/Library/Frameworks/Xamarin.Mac.framework/Versions"
        ls -la /Library/Frameworks/Xamarin.Mac.framework/Versions

    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: nuget restore Binding/Xam.Plugin.Mixpanel.Android.sln

    - name: Build
      run: |
        cd Binding/
        bash BuildNugetPackage.sh
    
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        files: |
          Binding/Xam.Plugin.Mixpanel.Android.*.nupkg
          Binding/Xam.Plugin.Mixpanel.Android.*.snupkg
          
    #- name: Upload nuget
    #  run: |
    #    cd Binding/
    #    nuget SetApiKey "${{ secrets.NUGET_API_KEY }}"
    #    nuget push *.nupkg -Source https://api.nuget.org/v3/index.json 
